export enum Role {
  SHOPPER = "SHOPPER",
  DESIGNER = "DESIGNER",
  BOUTIQUE = "BOUTIQUE",
  BRAND = "BRAND",
  INFLUENCER = "INFLUENCER",
  ADMIN = "ADMIN",
  PUBLIC = "PUBLIC",
  UNASSIGNED = "UNASSIGNED",
}
